### ISSUE TITLE
Add: How to render the sysext:core changelog with caching

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/TYPO3CMS-Guide-RenderTypo3Documentation#2]
See this little how-to at [slack](https://typo3.slack.com/archives/C028JEPJL/p1533202749000112) Make this a real how-to here.

**Comment by sypets** [comment]
See also section https://docs.typo3.org/typo3cms/ContributionWorkflowGuide/BugfixingAZ/Index.html#render-the-changelog in contribution guide. Since adding docs to the changelog is always done in combination with creating a patch, I think the information is best put in the contribution guide. The contribution guide also explains how to clone the source etc.

**Comment by sypets** [comment]
documented: https://docs.typo3.org/typo3cms/ContributionWorkflowGuide/AddingDocumentation/Index.html#render-the-changelog
